/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import api.ApiClient;
import api.Session;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author elsni
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setSize(620, 550);   
        setResizable(false); 
        aplicarDiseno();
        setLocationRelativeTo(null);
    }
    
    private void aplicarDiseno() {
        // Paleta tipo Athenaeum
        getRootPane().setBorder(new EmptyBorder(18, 24, 18, 24));
        
        getRootPane().setBorder(
            BorderFactory.createCompoundBorder(
                new EmptyBorder(18, 24, 18, 24),
                BorderFactory.createLineBorder(new Color(220, 210, 200), 1)
            )
        );
        
        Color maroon = new Color(125, 15, 25);
        Color cream  = new Color(249, 243, 238);
        Color borde  = new Color(220, 210, 200);

        // Fondo general
        getContentPane().setBackground(cream);

        // Título bonito
        jLabel1.setFont(new Font("Serif", Font.BOLD, 28));
        jLabel1.setForeground(maroon);

        // Logo arriba del texto usando el MISMO jLabel1 (sin crear otro)
        // Logo arriba (en lblLogo)
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/logo.png"));
            java.awt.Image img = icon.getImage();

            // Ajusta el tamaño del logo aquí sin empujar el contenido raro
            java.awt.Image imgEscalada = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);

            lblLogo.setIcon(new ImageIcon(imgEscalada));
            lblLogo.setText("");
            lblLogo.setHorizontalAlignment(SwingConstants.CENTER);

        } catch (Exception e) {
            lblLogo.setText(""); // sin logo no pasa nada
        }

        // Labels pequeños
        jLabel2.setFont(new Font("SansSerif", Font.BOLD, 14));
        jLabel2.setForeground(maroon);

        jLabel3.setFont(new Font("SansSerif", Font.BOLD, 14));
        jLabel3.setForeground(maroon);

        // Inputs con borde + padding
        CompoundBorder inputBorder = BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(borde, 1),
                new EmptyBorder(8, 10, 8, 10)
        );

        txtCorreo.setFont(new Font("SansSerif", Font.PLAIN, 14));
        txtCorreo.setBorder(inputBorder);

        txtPass.setFont(new Font("SansSerif", Font.PLAIN, 14));
        txtPass.setBorder(inputBorder);

        // Botón estilo
        btnLogin.setFont(new Font("SansSerif", Font.BOLD, 15));
        btnLogin.setBackground(maroon);
        btnLogin.setForeground(Color.WHITE);
        btnLogin.setFocusPainted(false);
        btnLogin.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(95, 10, 18), 1),
                new EmptyBorder(8, 18, 8, 18)
        ));
        btnLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Status (mensaje)
        lblStatus.setFont(new Font("SansSerif", Font.PLAIN, 13));
        lblStatus.setForeground(maroon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesión");

        jLabel2.setText("Correo");

        jLabel3.setText("Contraseña");

        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCorreo)
                        .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try {
            String correo = txtCorreo.getText().trim();
            String pass = new String(txtPass.getPassword());

            if (correo.isEmpty() || pass.isEmpty()) {
                lblStatus.setText("Correo y contraseña obligatorios");
                return;
            }

            Gson gson = new Gson();

            JsonObject body = new JsonObject();
            body.addProperty("correo", correo);
            body.addProperty("contraseña", pass);

            String response = ApiClient.postJson("/api/auth/login", gson.toJson(body));

            JsonObject json = gson.fromJson(response, JsonObject.class);

            // ✅ NUEVO: el API ya NO devuelve "user", devuelve los campos directos
            Session.token = json.get("token").getAsString();
            Session.idUsuario = json.get("id_usuario").getAsInt();
            Session.nombres = json.get("nombres").getAsString();
            Session.apellidos = json.get("apellidos").getAsString();
            Session.rol = json.get("rol").getAsString();

            // Solo ADMIN
            if (!"ADMIN".equalsIgnoreCase(Session.rol)) {
                Session.token = null;
                lblStatus.setText("No autorizado: solo ADMIN");
                return;
            }

            JOptionPane.showMessageDialog(this, "Bienvenido " + Session.nombres);

            new MenuAdminFrame().setVisible(true);
            this.dispose();

        } catch (Exception ex) {
            ex.printStackTrace();

            // Si tu ApiClient lanza RuntimeException con "HTTP 401 -> ..."
            String msg = ex.getMessage() == null ? "Error desconocido" : ex.getMessage();

            if (msg.contains("HTTP 401")) {
                lblStatus.setText("Credenciales inválidas");
            } else if (msg.contains("HTTP 403")) {
                lblStatus.setText("Usuario no activo / sin permisos");
            } else {
                lblStatus.setText("Error: " + msg);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
